### ISSUE TITLE
Great idea, but not yet usable

### ISSUE THREAD

**Issue by ouun** [bszyk/dynamic-block-content#7]
Hi @bszyk,

I stubled over your plugin here as it is exactly what I am searching for. A lightweight solution to get some dynamic field content as with the big Gutenberg libraries, but without the bloat.
However while a field content is displayed in the editor, on the frontend it is always replaces with `[[bszyk-dynamic-content]]`. So I am wondering if you are planning to work on this any further. 

Kind regards,

Philipp

**Comment by b-sik** [comment]
Hey @ouun , really glad you came across the plugin and took the time to comment. I've been looking for some motivation to work on this more, and it helps knowing someone could use this. With that being said, I'll take a look at the issue this evening/weekend, I thought the basic functionality was working.

**Comment by ouun** [comment]
@bszyk thanks for getting back to me that fast!
Yes, it will be of great help. In my scenario I am switching with a site from a very heavy ACF usage to the Block Editor and I would like to prefill some block content with existing fields. So this is a very basic requirement and this seems to solve it. Also I am sure that this will be helpful for many others, too. They simply don't know, yet. ;)

Thanks a lot and kind regards!

**Comment by b-sik** [comment]
@ouun Hey I found the issue and updated the plugin to v0.1.1, should be able to update from your WP site, and please let me know if it's working. Again, very glad you think this could be useful - while I was debugging I noticed a big limitation is it doesn't work when the block is nested inside another block, such as a column, so I believe that will be the next update I make.

Any thing in particular you'd like to see added next?

**Comment by ouun** [comment]
@bszyk thanks a lot! This is amazing and I can approve that it is working now as expected.
 
I got an additional feedback as testing it again:
At the moment it is possible to select any kind of meta field related to the post. Right?
Now  e.g. using ACF with repeater fields produces a whole bunch of meta fields that contain unusable content, as in the screenshot attached. What do you think about a kind of filter, that skips e.g. fields with serialized content? 

Again, thanks a lot!

<img width="779" alt="grafik" src="https://user-images.githubusercontent.com/32090713/172680825-06a95016-bc65-4e01-a067-c9853a5abf23.png">

**Comment by b-sik** [comment]
@ouun Check out the newest version, should auto remove any value that is serialized data. Also gives me the idea to add filter options server-side and client-side. Thanks again for the feedback!
